Fix error in circuit-breaker example config (#1098)
Was experimenting with the circuit breaker today for a blog post and
noticed the config in the example fails because `tripped_duration` is
set to `3m` when the maximum is `2m`:

```
ERROR:  failed to start tunnel: Failed to parse configuration for circuit-breaker: tripped_duration must be between 1s and 2m0s inclusive, was seconds:180.
```